version: '3.1'
services:
    app:
        container_name: classroom-app
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
        networks:
            - classroom-app
    nginx:
        image: nginx:alpine
        container_name: nginx-classroom
        ports:
            - "8001:80"
        volumes:
            - ./docker/:/var/www:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - app
        networks:
            - classroom-app
    mysql:
        image: mysql:8.0
        container_name: classroom-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: classroom-db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3310:3306
        networks:
            - classroom-app
    redis:
        image: redis:latest
        ports:
            - 6384:6379
        volumes:
            - ./docker/redis:/data
        networks:
            - classroom-app
    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis-commander
        ports:
            - "8081:8081"
        environment:
            - REDIS_HOSTS=local:redis:6379
        depends_on:
            - redis
        networks:
            - classroom-app
networks:
    classroom-app:
